version: '2'

services:
  cli:
    tty: true
    image: hyperledger/fabric-tools:x86_64-1.0.0
    environment:
      - GOPATH=/opt/gopath
      - CORE_LOGGING_LEVEL=DEBUG

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/crypto/peer/tls/ca.crt
      
      - ORDERER_CA=/var/hyperledger/crypto/orderer/msp/tlscacerts/tlsca.art.ifar.org-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ../artifacts/orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ../artifacts/chaincode:/opt/gopath/src/chaincode
      - ../artifacts/channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ../logs/:/opt/gopath/src/github.com/hyperledger/fabric/peer/logs

